#!/bin/bash
# Generate secrets for Langfuse Docker stack
# Called by: make setup-secrets

set -e

cd "$(dirname "$0")/.."

echo "🔐 Generating Langfuse secrets..."

# Generate random secrets
NEXTAUTH_SECRET=$(openssl rand -hex 32)
SALT=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -hex 32)

# Generate API keys (fixed format for easy use)
# These are pre-configured so you don't need to log in
PUBLIC_KEY="pk-lf-$(openssl rand -hex 16)"
SECRET_KEY="sk-lf-$(openssl rand -hex 16)"

# Check if .env exists
if [ ! -f .env ]; then
    echo "   Creating new .env file..."
    cat > .env << EOF
# Auto-generated by make setup-secrets
# Edit as needed

# LLM Provider (uncomment one)
# LLM_PROVIDER=openai
# OPENAI_API_KEY=sk-xxx

# Local LLM (llama.cpp)
LLM_PROVIDER=local
LOCAL_API_KEY=local
LLM_BASE_URL=http://localhost:8001/v1

# llama.cpp Docker
LLM_MODEL_PATH=/path/to/your/llm-model.gguf
EMBED_MODEL_PATH=/path/to/your/embedding-model.gguf
LLAMA_PORT=8001

# MCP Scraper
MCP_HOST=100.85.22.99
MCP_PORT=8000

# Langfuse Observability (auto-configured, no login needed)
LANGFUSE_BASE_URL=http://localhost:3000
LANGFUSE_PUBLIC_KEY=${PUBLIC_KEY}
LANGFUSE_SECRET_KEY=${SECRET_KEY}

# Docker internal secrets (auto-generated)
LANGFUSE_NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
LANGFUSE_SALT=${SALT}
LANGFUSE_ENCRYPTION_KEY=${ENCRYPTION_KEY}
LANGFUSE_DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
LANGFUSE_POSTGRES_PASSWORD=langfuse
LANGFUSE_CLICKHOUSE_PASSWORD=clickhouse
LANGFUSE_REDIS_AUTH=redissecret
LANGFUSE_MINIO_ROOT_USER=minio
LANGFUSE_MINIO_ROOT_PASSWORD=miniosecret
LANGFUSE_INIT_USER_EMAIL=admin@example.com
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=password123
EOF
    echo "   ✅ Created .env with generated secrets"
else
    # Update existing .env
    echo "   Updating existing .env..."

    # Check if we need to add secrets
    if ! grep -q "LANGFUSE_NEXTAUTH_SECRET" .env; then
        cat >> .env << EOF

# Docker internal secrets (auto-generated)
LANGFUSE_NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
LANGFUSE_SALT=${SALT}
LANGFUSE_ENCRYPTION_KEY=${ENCRYPTION_KEY}
LANGFUSE_DATABASE_URL=postgresql://langfuse:langfuse@postgres:5432/langfuse
LANGFUSE_POSTGRES_PASSWORD=langfuse
LANGFUSE_CLICKHOUSE_PASSWORD=clickhouse
LANGFUSE_REDIS_AUTH=redissecret
LANGFUSE_MINIO_ROOT_USER=minio
LANGFUSE_MINIO_ROOT_PASSWORD=miniosecret
LANGFUSE_INIT_USER_EMAIL=admin@example.com
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=password123
EOF
        echo "   ✅ Added secrets to .env"
    else
        echo "   ✅ Secrets already present"
    fi

    # Add API keys if not present
    if ! grep -q "LANGFUSE_PUBLIC_KEY=." .env || grep -q "LANGFUSE_PUBLIC_KEY=pk-lf-\.\.\." .env; then
        # Update the placeholder keys with real ones
        sed -i "s|^LANGFUSE_PUBLIC_KEY=.*|LANGFUSE_PUBLIC_KEY=${PUBLIC_KEY}|" .env
        sed -i "s|^LANGFUSE_SECRET_KEY=.*|LANGFUSE_SECRET_KEY=${SECRET_KEY}|" .env
        echo "   ✅ Added API keys to .env"
    fi
fi

echo ""
echo "Generated:"
echo "  NEXTAUTH_SECRET:   ${NEXTAUTH_SECRET:0:16}..."
echo "  PUBLIC_KEY:        ${PUBLIC_KEY}"
echo "  SECRET_KEY:        ${SECRET_KEY:0:16}..."
echo ""
echo "📋 API Keys (add to your .env if not auto-added):"
echo "   LANGFUSE_PUBLIC_KEY=${PUBLIC_KEY}"
echo "   LANGFUSE_SECRET_KEY=${SECRET_KEY}"
